# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: postgres:13.3
        restart: always
        environment:
            POSTGRES_USER: mmuser
            POSTGRES_PASSWORD: mostest
            POSTGRES_DB: automation_dashboard_db
        ports:
            - 5435:5432

    adminer:
        image: adminer:4.8.1
        restart: always
        ports:
            - 5436:8080
